apiVersion: v1
kind: Service
metadata:
  name: dbserver-k8s-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
   - name: "db-port"
     protocol: "TCP"
     port: 5432
     targetPort: 5432
  selector:
    app: dbserver-k8s-sfs
