apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 
    dbserver-k8s-sfs
spec:
  serviceName: dbserver-k8s-service
  replicas: 1
  selector:
    matchLabels:
      app: dbserver-k8s-sfs
  template:
    metadata:
      labels:
        app: dbserver-k8s-sfs
    spec:
      containers:
       - name: dbserver
         image: dbserver_k8s:1.0
         ports:
          - containerPort: 5432
         volumeMounts:
         - name: pvc-db-volume
           mountPath: /var/lib/postgresql
  volumeClaimTemplates:
  - metadata:
      name: pvc-db-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1G

