apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-k8s
  template:
    metadata:
      labels:
        app: webserver-k8s
    spec:
      containers:
      - name: nginx
        image: webserver_k8s:1.0
        ports:
        - containerPort: 80
