apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
    appserver-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appserver-k8s
  template:
    metadata:
      labels:
        app: appserver-k8s
    spec:
      containers:
      - name: appserver
        image: appserver_k8s:1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
          - name: DB_URL
            value: "jdbc:postgresql://dbserver-k8s-service:5432/testdb"
          - name: DB_USERNAME
            value: "testusr"
          - name: DB_PASSWORD
            value: "testusr"
          - name: REDIS_HOST
            value: "redis-k8s-service"
          - name: REDIS_PORT
            value: "6379"     
